# 
# Synthesis run script generated by Vivado
# 

set_msg_config  -ruleid {1}  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/3A/UART_SystremC_RGB2YUV/src/UART_fifoed_send_V1.vhd'.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vivado/UART_RGB2YUV.cache/wt [current_project]
set_property parent.project_path /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vivado/UART_RGB2YUV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/RGB2YCbCr.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_t/UART_fifoed_send_V1.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_r/uart_recv.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_r/merger_8b_to_24b.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_r/full_uart_recv.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_t/splitter_24b_to_8b.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/uart_t/full_uart_trans.vhd
  /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/vhdl/top_uart.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/xdc/nexys_4.xdc
set_property used_in_implementation false [get_files /home/legal/EN325-Advanced-digital-design/5_FPGA/1_FPGASynthesis/xdc/nexys_4.xdc]


synth_design -top top_uart -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_uart.dcp

catch { report_utilization -file top_uart_utilization_synth.rpt -pb top_uart_utilization_synth.pb }
